default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: meu_app_development

test:
  <<: *default
  database: meu_app_test

production:
  <<: *default
  database: meu_app_production
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
